// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE
'use strict';

var WithAuthenticatorGen = require("./WithAuthenticator.gen");

var make = WithAuthenticatorGen.withAuthenticator;

var $$default = make;

exports.make = make;
exports.$$default = $$default;
exports.default = $$default;
exports.__esModule = true;
/* make Not a pure module */
