/* Untyped file generated by genType. */

import {withAuthenticator as withAuthenticatorNotChecked} from 'aws-amplify-react';

// In case of type error, check the type of 'withAuthenticator' in 'WithAuthenticator.re' and 'aws-amplify-react'.
export const withAuthenticatorTypeChecked = withAuthenticatorNotChecked;

// Export 'withAuthenticator' early to allow circular import from the '.bs.js' file.
export const withAuthenticator = withAuthenticatorTypeChecked;
